name: Deploy to ECS

on:
  push:
    branches:
      - "dev"
      - "prod"

permissions:
  id-token: write   # necessário para OIDC
  contents: read    # necessário para checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Definir variáveis de ambiente com base na branch
      - name: Set environment by branch
        run: |
          if [[ "${GITHUB_REF##*/}" == "prod" ]]; then
            echo "ECR_REPO=my-app-prod" >> $GITHUB_ENV
            echo "SERVICE=my-app-
